[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.16"
optimizer = true
optimizer_runs = 1000000
via_ir = true

[default.optimizer_details]
stack_allocation = true
constantOptimizer = true
yul = true
